import 'package:flutter/material.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = [
    Locale('en'),
    Locale('ru'),
    Locale('uk'),
  ];

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  String get languageName {
    switch (locale.languageCode) {
      case 'ru':
        return 'Русский';
      case 'uk':
        return 'Українська';
      default:
        return 'English';
    }
  }

  static const Map<String, Map<String, String>> _strings = {
    'en': {
      'app_title': 'Focus Timer',
      'home_title': 'Start Now',
      'today_focused': 'Today focused',
      'minutes_short': 'min',
      'sessions_today': 'Sessions today',
      'current_streak': 'Current streak',
      'days_short': 'days',
      'your_progress': 'Your Progress',
      'today_section': 'Today',
      'focused_label': 'Focused',
      'sessions_label': 'Sessions',
      'streaks_section': 'Streaks',
      'best_streak': 'Best streak',
      'weekly_overview': 'Weekly Overview',
      'calendar_heatmap': 'Calendar Heatmap',
      'unlock_stats': 'Unlock Stats',
      'premium_feature': 'Premium feature',
      'focus_sounds': 'Focus Sounds',
      'volume': 'Volume',
      'auto_play': 'Auto play with timer',
      'sound_rain': 'Rain',
      'sound_ocean': 'Ocean',
      'sound_forest': 'Forest',
      'sound_fire': 'Fireplace',
      'sound_white': 'White Noise',
      'sound_button': 'Sound',
      'reminders': 'Reminders',
      'daily_reminder': 'Daily Focus Reminder',
      'inactivity_reminder': 'Inactivity Reminder',
      'streak_reminder': 'Streak Reminder',
      'quiet_hours': 'Quiet Hours',
      'time': 'Time',
      'after_time': 'After',
      'send_after': 'Send after',
      'from': 'From',
      'to': 'To',
      'sessions_completed': 'Sessions completed: {count}',
      'start_now': 'Start Now',
      'start_now_subtitle': 'Anti-procrastination',
      'pomodoro': 'Pomodoro',
      'pomodoro_subtitle': 'Focus + break',
      'deep_work': 'Deep Work',
      'study': 'Study',
      'sprint': 'Sprint',
      'long_focus': 'Long Focus',
      'presets': 'Presets',
      'see_all': 'See all',
      'preset': 'Preset',
      'free': 'Free',
      'premium': 'Premium',
      'create_preset': 'Create preset',
      'edit_preset': 'Edit preset',
      'preset_name': 'Preset name',
      'preset_name_placeholder': 'Name',
      'auto_start_break': 'Auto-start break',
      'auto_start_next_focus': 'Auto-start next focus',
      'delete_preset': 'Delete preset',
      'change_preset_title': 'Change preset?',
      'change_preset_body': 'Changing preset will reset the timer. Continue?',
      'reset': 'Reset',
      'custom_preset': 'Custom',
      'customize': 'Customize',
      'customize_premium': 'Customize (Premium)',
      'customize_locked_subtitle': 'Presets & white noise',
      'small_rule': 'Small rule',
      'small_rule_text': "If you can't start, do 5 minutes. Starting is the win.",
      'focus': 'Focus',
      'break': 'Break',
      'ready_when': 'Ready when you are.',
      'start': 'Start',
      'end': 'End',
      'pause': 'Pause',
      'nice_again': 'Nice. Want to go again?',
      'back_home': 'Back Home',
      'start_again': 'Start Again',
      'upgrade': 'Upgrade',
      'unlock_deep_focus': 'Unlock Deep Focus',
      'upgrade_subtitle': 'Build a routine. Track progress.',
      'custom_timers': 'Custom timers',
      'custom_timers_subtitle': 'Set your own intervals',
      'presets_subtitle': 'Deep Work, Study and more',
      'stats_streaks': 'Stats & streaks',
      'stats_streaks_subtitle': 'See your progress',
      'white_noise': 'White noise',
      'white_noise_subtitle': 'Focus with sound',
      'smart_reminders': 'Smart reminders',
      'smart_reminders_subtitle': 'Stay on track',
      'weekly': 'Weekly',
      'yearly': 'Yearly',
      'price_weekly': '€2.99 / week',
      'price_yearly': '€29.99 / year',
      'most_popular': 'Most popular',
      'best_value': 'Best value',
      'continue': 'Subscribe',
      'not_now': 'Not now',
      'paywall_title': 'Unlock Your Full Potential',
      'paywall_subtitle': 'Get instant access to all premium features!',
      'start_free_trial': 'Start Free Trial',
      'trial_caption': '3 days free, then €2.99 / week. Cancel anytime.',
      'restore_purchase': 'Restore Purchase',
      'privacy_policy': 'Privacy Policy',
      'save_50': 'Save 50%',
      'settings': 'Settings',
      'theme': 'Theme',
      'theme_system': 'System',
      'theme_light': 'Light',
      'theme_dark': 'Midnight',
      'language': 'Language',
      'system_default': 'System default',
      'customize_timer': 'Customize timer',
      'focus_minutes': 'Focus minutes',
      'break_minutes': 'Break minutes',
      'save': 'Save',
      'cancel': 'Cancel',
      'debug_premium': 'Premium (debug)',
    },
    'ru': {
      'app_title': 'Фокус Таймер',
      'home_title': 'Старт сейчас',
      'today_focused': 'Сегодня в фокусе',
      'minutes_short': 'мин',
      'sessions_today': 'Сессий сегодня',
      'current_streak': 'Текущая серия',
      'days_short': 'дней',
      'your_progress': 'Ваш прогресс',
      'today_section': 'Сегодня',
      'focused_label': 'Фокус',
      'sessions_label': 'Сессии',
      'streaks_section': 'Серии',
      'best_streak': 'Лучшая серия',
      'weekly_overview': 'Неделя',
      'calendar_heatmap': 'Календарь',
      'unlock_stats': 'Открыть статистику',
      'premium_feature': 'Премиум‑функция',
      'focus_sounds': 'Фокус‑звуки',
      'volume': 'Громкость',
      'auto_play': 'Автозапуск с таймером',
      'sound_rain': 'Дождь',
      'sound_ocean': 'Океан',
      'sound_forest': 'Лес',
      'sound_fire': 'Камин',
      'sound_white': 'Белый шум',
      'sound_button': 'Звук',
      'reminders': 'Напоминания',
      'daily_reminder': 'Ежедневное напоминание',
      'inactivity_reminder': 'Напоминание о бездействии',
      'streak_reminder': 'Напоминание о серии',
      'quiet_hours': 'Тихие часы',
      'time': 'Время',
      'after_time': 'После',
      'send_after': 'Отправлять после',
      'from': 'С',
      'to': 'До',
      'sessions_completed': 'Сессий завершено: {count}',
      'start_now': 'Старт сейчас',
      'start_now_subtitle': 'Антипрокрастинация',
      'pomodoro': 'Помодоро',
      'pomodoro_subtitle': 'Фокус + перерыв',
      'deep_work': 'Глубокая работа',
      'study': 'Учёба',
      'sprint': 'Спринт',
      'long_focus': 'Длинный фокус',
      'presets': 'Пресеты',
      'see_all': 'Все',
      'preset': 'Пресет',
      'free': 'Бесплатно',
      'premium': 'Премиум',
      'create_preset': 'Создать пресет',
      'edit_preset': 'Редактировать пресет',
      'preset_name': 'Название',
      'preset_name_placeholder': 'Название',
      'auto_start_break': 'Автостарт перерыва',
      'auto_start_next_focus': 'Автостарт следующего фокуса',
      'delete_preset': 'Удалить пресет',
      'change_preset_title': 'Сменить пресет?',
      'change_preset_body': 'Смена пресета сбросит таймер. Продолжить?',
      'reset': 'Сбросить',
      'custom_preset': 'Свои',
      'customize': 'Настроить',
      'customize_premium': 'Настроить (Премиум)',
      'customize_locked_subtitle': 'Пресеты и белый шум',
      'small_rule': 'Малое правило',
      'small_rule_text': 'Не можешь начать — сделай 5 минут. Начать — уже победа.',
      'focus': 'Фокус',
      'break': 'Перерыв',
      'ready_when': 'Готов, когда будешь ты.',
      'start': 'Старт',
      'end': 'Стоп',
      'pause': 'Пауза',
      'nice_again': 'Отлично. Повторим?',
      'back_home': 'На главную',
      'start_again': 'Начать снова',
      'upgrade': 'Апгрейд',
      'unlock_deep_focus': 'Открой глубокий фокус',
      'upgrade_subtitle': 'Сформируй рутину. Отслеживай прогресс.',
      'custom_timers': 'Свои таймеры',
      'custom_timers_subtitle': 'Задай свои интервалы',
      'presets_subtitle': 'Deep Work, Study и другие',
      'stats_streaks': 'Статистика и серии',
      'stats_streaks_subtitle': 'Смотри свой прогресс',
      'white_noise': 'Белый шум',
      'white_noise_subtitle': 'Фокус со звуком',
      'smart_reminders': 'Умные напоминания',
      'smart_reminders_subtitle': 'Держи ритм',
      'weekly': 'Неделя',
      'yearly': 'Год',
      'price_weekly': '€2.99 / неделя',
      'price_yearly': '€29.99 / год',
      'most_popular': 'Самый популярный',
      'best_value': 'Лучшая цена',
      'continue': 'Оформить подписку',
      'not_now': 'Не сейчас',
      'paywall_title': 'Раскрой свой потенциал',
      'paywall_subtitle': 'Мгновенный доступ ко всем премиум‑функциям!',
      'start_free_trial': 'Начать пробный период',
      'trial_caption': '3 дня бесплатно, затем €2.99 / неделя. Отмена в любой момент.',
      'restore_purchase': 'Восстановить покупки',
      'privacy_policy': 'Политика конфиденциальности',
      'save_50': 'Скидка 50%',
      'settings': 'Настройки',
      'theme': 'Тема',
      'theme_system': 'Системная',
      'theme_light': 'Светлая',
      'theme_dark': 'Полуночная',
      'language': 'Язык',
      'system_default': 'Системный',
      'customize_timer': 'Настроить таймер',
      'focus_minutes': 'Минуты фокуса',
      'break_minutes': 'Минуты перерыва',
      'save': 'Сохранить',
      'cancel': 'Отмена',
      'debug_premium': 'Премиум (debug)',
    },
    'uk': {
      'app_title': 'Фокус Таймер',
      'home_title': 'Почати зараз',
      'today_focused': 'Сьогодні у фокусі',
      'minutes_short': 'хв',
      'sessions_today': 'Сесій сьогодні',
      'current_streak': 'Поточна серія',
      'days_short': 'днів',
      'your_progress': 'Ваш прогрес',
      'today_section': 'Сьогодні',
      'focused_label': 'Фокус',
      'sessions_label': 'Сесії',
      'streaks_section': 'Серії',
      'best_streak': 'Найкраща серія',
      'weekly_overview': 'Тиждень',
      'calendar_heatmap': 'Календар',
      'unlock_stats': 'Відкрити статистику',
      'premium_feature': 'Преміум‑функція',
      'focus_sounds': 'Фокус‑звуки',
      'volume': 'Гучність',
      'auto_play': 'Автозапуск з таймером',
      'sound_rain': 'Дощ',
      'sound_ocean': 'Океан',
      'sound_forest': 'Ліс',
      'sound_fire': 'Камін',
      'sound_white': 'Білий шум',
      'sound_button': 'Звук',
      'reminders': 'Нагадування',
      'daily_reminder': 'Щоденне нагадування',
      'inactivity_reminder': 'Нагадування про бездіяльність',
      'streak_reminder': 'Нагадування про серію',
      'quiet_hours': 'Тихі години',
      'time': 'Час',
      'after_time': 'Після',
      'send_after': 'Надсилати після',
      'from': 'З',
      'to': 'До',
      'sessions_completed': 'Сесій завершено: {count}',
      'start_now': 'Почати зараз',
      'start_now_subtitle': 'Антипрокрастинація',
      'pomodoro': 'Помодоро',
      'pomodoro_subtitle': 'Фокус + перерва',
      'deep_work': 'Глибока робота',
      'study': 'Навчання',
      'sprint': 'Спринт',
      'long_focus': 'Довгий фокус',
      'presets': 'Пресети',
      'see_all': 'Усі',
      'preset': 'Пресет',
      'free': 'Безкоштовно',
      'premium': 'Преміум',
      'create_preset': 'Створити пресет',
      'edit_preset': 'Редагувати пресет',
      'preset_name': 'Назва',
      'preset_name_placeholder': 'Назва',
      'auto_start_break': 'Автозапуск перерви',
      'auto_start_next_focus': 'Автозапуск наступного фокусу',
      'delete_preset': 'Видалити пресет',
      'change_preset_title': 'Змінити пресет?',
      'change_preset_body': 'Зміна пресету скине таймер. Продовжити?',
      'reset': 'Скинути',
      'custom_preset': 'Свій',
      'customize': 'Налаштувати',
      'customize_premium': 'Налаштувати (Преміум)',
      'customize_locked_subtitle': 'Пресети та білий шум',
      'small_rule': 'Мале правило',
      'small_rule_text': 'Не можеш почати — зроби 5 хвилин. Почати — вже перемога.',
      'focus': 'Фокус',
      'break': 'Перерва',
      'ready_when': 'Готовий, коли ти.',
      'start': 'Старт',
      'end': 'Стоп',
      'pause': 'Пауза',
      'nice_again': 'Чудово. Повторимо?',
      'back_home': 'На головну',
      'start_again': 'Почати знову',
      'upgrade': 'Оновлення',
      'unlock_deep_focus': 'Відкрий глибокий фокус',
      'upgrade_subtitle': 'Побудуй рутину. Відстежуй прогрес.',
      'custom_timers': 'Власні таймери',
      'custom_timers_subtitle': 'Задай свої інтервали',
      'presets_subtitle': 'Deep Work, Study та інші',
      'stats_streaks': 'Статистика і серії',
      'stats_streaks_subtitle': 'Дивись свій прогрес',
      'white_noise': 'Білий шум',
      'white_noise_subtitle': 'Фокус зі звуком',
      'smart_reminders': 'Розумні нагадування',
      'smart_reminders_subtitle': 'Тримай ритм',
      'weekly': 'Тиждень',
      'yearly': 'Рік',
      'price_weekly': '€2.99 / тиждень',
      'price_yearly': '€29.99 / рік',
      'most_popular': 'Найпопулярніший',
      'best_value': 'Найкраща ціна',
      'continue': 'Оформити підписку',
      'not_now': 'Не зараз',
      'paywall_title': 'Розкрий свій потенціал',
      'paywall_subtitle': 'Миттєвий доступ до всіх преміум‑функцій!',
      'start_free_trial': 'Почати безкоштовну пробу',
      'trial_caption': '3 дні безкоштовно, потім €2.99 / тиждень. Скасувати будь‑коли.',
      'restore_purchase': 'Відновити покупки',
      'privacy_policy': 'Політика конфіденційності',
      'save_50': 'Знижка 50%',
      'settings': 'Налаштування',
      'theme': 'Тема',
      'theme_system': 'Системна',
      'theme_light': 'Світла',
      'theme_dark': 'Опівнічна',
      'language': 'Мова',
      'system_default': 'Системна',
      'customize_timer': 'Налаштувати таймер',
      'focus_minutes': 'Хвилини фокусу',
      'break_minutes': 'Хвилини перерви',
      'save': 'Зберегти',
      'cancel': 'Скасувати',
      'debug_premium': 'Преміум (debug)',
    },
  };

  String t(String key, {Map<String, String> params = const {}}) {
    final lang = _strings[locale.languageCode] ?? _strings['en']!;
    var value = lang[key] ?? _strings['en']![key] ?? key;
    params.forEach((param, replacement) {
      value = value.replaceAll('{$param}', replacement);
    });
    return value;
  }
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return AppLocalizations.supportedLocales
        .any((supported) => supported.languageCode == locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
